eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
info:
  app:
    name: microservice-example
    description: This is an example of a microservice
    version: 1.0.0
  author: Thalles
  mail: thalles@email.com
server:
  port: ${PORT:9999}
message: Test application.yml
